config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  
  resources :users

  resources :posts, except: [:index] do
    resources :comments, except: [:index]
  end

  resources :sessions, only: [:new, :create, :destroy]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  after_create :send_sms

  belongs_to :post
  belongs_to :user

  validates :body, :presence => true

  scope :by_date, -> { order(created_at: :desc) }

private
  def send_sms
    begin
      number_to_send_to = @post.user.number

      response = RestClient::Request.new(
        :method => :post,
        :url => "https://api.twilio.com/2010-04-01/Accounts/#{ENV['TWILIO_ACCOUNT_SID']}/Messages.json",
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => "You have a new comment waiting for you.", :From => ENV["TWILIO_PHONE_NUMBER"], :To => number_to_send_to }
      ).execute

    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      false
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :title, :presence => true
  validates :body, :presence => true

  has_attached_file :image, :styles => { :large => "500x500>", :thumb => "100x100>" }, :default_url => "missing_image.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  scope :by_date, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  attr_accessor :password

  validates_confirmation_of :password
  before_save :encrypt_password

  validates :name, :presence => true
  validates :email, :presence => true
  validates :number, :presence => true
  validates :password, :presence => true
  validates :password_confirmation, :presence => true
  validates_uniqueness_of :email
  validates_uniqueness_of :number

  has_attached_file :avatar, :styles => { :medium => "250x250>", :thumb => "100x100>" }, :default_url => "missing_image.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  scope :by_date, -> { order(created_at: :desc) }

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html, :js

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comments_params)
    @comment.user_id = current_user.id
    flash[:notice] = "Comment successfully added!"
    if !@comment.save
      render :new
    end
  end


  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:post_id])
    @comment= Comment.find(params[:id])
    if @comment.update(comments_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end


  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "Comment successfully deleted."
    redirect_to post_path(@post)
  end

  private
  def comments_params
    params.require(:comment).permit(:body, :user_id, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    render :index
  end

  def show
    @comments = Comment.all
    @post = Post.find(params[:id])
    @user = User.find(@post.user_id)
    render :show
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(posts_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to user_path(@post.user_id)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(posts_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Post deleted!"
    redirect_to user_path(@post.user_id)
  end

private
  def posts_params
    params.require(:post).permit(:title, :body, :image, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are now logged out."
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to users_path
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      flash[:notice] = "Tricky fox, this isn't your profile!"
      redirect_to users_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = @user.name + "'s details edited!"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user != current_user
      flash[:notice] = "Tricky fox, this isn't your profile!"
      redirect_to users_path
    else
      session[:user_id] = nil
      @user.destroy
      flash[:notice] = "Profile destroyed!"
      redirect_to users_path
    end
  end

private
  def user_params
    params.require(:user).permit(:avatar, :number, :name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="well">
  <b><%= link_to user_path(comment.user) do %><%= comment.user.name %><% end %> says:</b><br>
  <span class="comment"><%= comment.body %></span><br>
  <small>
    <p class="text-right">
      <%= comment.created_at.to_formatted_s(:long_ordinal) %><% if comment.user == current_user %> |
      <%= link_to edit_post_comment_path(@post, comment) do %><i class="fa fa-cog"></i> Edit Comment<% end %> |
      <%= link_to post_comment_path(@post, comment), :data => {:confirm => "Do you really want to delete this comment?", :method => "delete"} do %><i class="fa fa-trash-o"></i> Delete Comment<% end %><% end %>
    </p>
  </small>
</div>

app/views/comments/_form.html.erb
<%= render "layouts/errors", :object => @comment %>

<%= form_for [@user, @post, @comment], remote:true do |f| %>
  <ul class="formList list-unstyled">

    <li>
      <%= f.label :body %><br>
      <%= f.text_area :body, :cols => "60", :rows => "10" %>
    </li>

    <li class="submit">
      <%= f.submit "Submit", :class => "btn btn-sm btn-success" %>
    </li>
  </ul>
<% end %>

app/views/comments/create.js.erb
$('#new_comment').remove();
$('#new_comment_button').show();
$('#no_comments').hide();
$('#comments').prepend('<%= j render(@comment) %>');

app/views/comments/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>Edit Comment</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render "layouts/errors", :object => @comment %>

    <%= form_for [@user, @post, @comment], :html => { :multipart => true} do |f| %>
      <ul class="formList list-unstyled">

        <li>
          <%= f.label :body %><br>
          <%= f.text_area :body, :cols => "60", :rows => "10" %>
        </li>

        <li class="submit">
          <%= f.submit "Submit", :class => "btn btn-sm btn-success" %>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>New Comment</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/comments/new.js.erb
$('#new_comment_button').hide().after('<%= j render("form") %>');

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="well">
    <h5>Please fix the following errors:</h5>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Woodland Log</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1><%= link_to "Woodland Log", users_path %></h1>
      </div>
      <div class="col-md-6 text-right">
        <p>
          <i class="fa fa-pagelines"></i>
          <% if current_user %>
            <%= link_to "My Profile", user_path(current_user) %>
            <i class="fa fa-tree"></i>
            <%= link_to session_path(current_user), :data => { :method => :delete } do %>Logout<% end %>
          <% else %>
            <%= link_to new_user_path do %>Register<% end %>
            <i class="fa fa-tree"></i>
            <%= link_to new_session_path do %>Login<% end %>
          <% end %>
        <i class="fa fa-leaf"></i></p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <hr>
        <%= yield %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">
        <%= flash[:alert] %>
        <%= flash[:notice] %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for [@user, @post], :html => { :multipart => true} do |f| %>
  <ul class="formList list-unstyled">
    <li>
      <%= f.label :title %><br>
      <%= f.text_field :title, :size => "61" %>
    </li>

    <li>
      <%= f.label :body %><br>
      <%= f.text_area :body, :cols => "60", :rows => "10" %>
    </li>

    <li>
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </li>

    <li class="submit">
      <%= f.submit "Submit", :class => "btn btn-sm btn-success" %>
    </li>
  </ul>
<% end %>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>Edit Post</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>New Post</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="col-md-8 col-md-offset-2">
  <h3>
    <%= @post.title %><br>
    <small>
      Posted by <%= link_to user_path(@post.user) do%><%= @post.user.name %><% end %> on <%= @post.created_at.to_formatted_s(:long_ordinal) %>
    </small>
  </h3>
  <hr>
  <span class="text-center">
    <p><%= link_to (image_tag @post.image.url(:large)), @post.image.url %></p>
  </span>
  <hr>
  <p><%= @post.body %></p>
  <small>
    <p class="text-right">
      <%= link_to edit_post_path(@post) do %><i class="fa fa-cog"></i> Edit Post<% end %> |
      <%= link_to post_path(@post), :data => {:confirm => "Do you really want to delete this post?", :method => "delete"} do %><i class="fa fa-trash-o"></i> Delete Post<% end %>
    </p>
  </small>
  <hr>

  <h4 class="text-center">
    <% if !current_user %>
      Login to join the conversation
    <% else %>
      <%= link_to new_post_comment_path(@post), remote: true, id: "new_comment_button", :class => "btn btn-sm btn-primary" do %><i class="fa fa-comments-o"></i> Add Comment<% end %>
    <% end %>
  </h4>

  <% if @post.comments.any? %>
     <div id="comments">
       <%= render @comments %>
     </div>
   <% else %>
     <h2 id="no_comments">No comments, yet!</h2>
     <div id="comments"></div>
   <% end %>
</div>

app/views/users/_form.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for @user, :html => { :mulitpart => true} do |f| %>
  <ul class="formList list-unstyled">
    <li>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </li>

    <li>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </li>

    <li>
      <%= f.label :number %><br>
      <%= f.text_field :number %>
    </li>

    <li>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </li>

    <li>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </li>

    <li>
      <%= f.label :avatar %>
      <%= f.file_field :avatar, :class => "well" %>
    </li>

    <li class="submit">
      <%= f.submit "Submit", :class => "btn btn-sm btn-success" %>
    </li>
  </ul>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>Edit User Info</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<% if @users.any? %>
  <h3>Loggers:</h3>

  <div class="col-md-8 col-md-offset-2"
    <div class="row">
      <% @users.by_date.each do |user| %>
        <div class="col-md-3 text-center user-tile">
          <%= link_to user_path(user) do %>
            <div class="row height">
              <%= image_tag user.avatar.url(:thumb) %>
            </div>
            <div class="row">
              <%= user.name %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <!-- </div> -->

<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>New User</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag @user.avatar.url(:medium) %>
  </div>
  <div class="col-md-9">
    <div class="row">
      <h3><%= @user.name %></h3>
      <h4><%= @user.email %></h4>
      <small>Member since: <%= @user.created_at.to_formatted_s(:long_ordinal) %></small>
    </div>
    <% if @user == current_user %>
      <div class="row" id="new-post">
        <p><%= link_to new_post_path(current_user), :class => "btn btn-sm btn-success" do %><i class="fa fa-pencil"></i> New Post<% end %></p>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @user.posts.any? %>
      <hr>
      <h2>Posts</h2>
      <% @user.posts.by_date.each do |post| %>
        <div class="row">
          <div class="col-md-6 col-md-offset-2">
            <h4>
              <%= link_to post_path(post) do %><%= post.title %><% end %><br>
              <small>
                <%= post.created_at.to_formatted_s(:long_ordinal) %>
              </small>
            </h4>
          </div>
          <div class="col-md-2 text-right">
            <% if @user == current_user %>
              <p>
                <%= link_to edit_post_path(post) do %><i class="fa fa-cog"></i> Edit Post<% end %><br>
                <%= link_to post_path(post), :data => {:confirm => "Do you really want to delete this post?", :method => "delete"} do %><i class="fa fa-trash-o"></i> Delete Post<% end %>
              </p>
            <% end %>
          </div>
          <div class="col-md-8 col-md-offset-2">
            <hr>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <p>
      <%= link_to "Return Home", users_path %>
      <% if @user == current_user %>
        | <%= link_to edit_user_path(@user) do %><i class="fa fa-cog"></i> Edit Profile<% end %> |
        <%= link_to user_path(@user), :data => {:confirm => "Do you really want to delete your profile?", :method => "delete"} do %><i class="fa fa-trash-o"></i> Delete Profile<% end %>
      <% end %>
    </p>
  </div>
</div>